# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ code to to partition a bipartite network into non-overlapping biclusters, by optimizing bipartite modularity.
#'
#' @param nr Number of rows of incidence matrix.
#' @param nc Number of columns of incidence matrix.
#' @param data Vectorized incidence matrix.
#' @param ITER Number of iterations.
#' @return MODULARITY Modularity value.
#' @return ASSIGN Partition of rows and columns.
#' @export
CoClust <- function(nr, nc, data, ITER) {
    .Call(`_BipartiteModularityMaximization_CoClust`, nr, nc, data, ITER)
}

